packages:
  - 'examples/*'
  - 'packages/*'
  - 'apps/*'

catalog:
  '@goat-sdk/core': '^0.4.6'
  'zod': '^3.24.1'
  'tsup': '^8.0.2'
  'dotenv': '^16.4.5'
  'tsx': '^4.7.1'
  'typescript': '^5.3.3'
  'vitest': '^1.2.1'
  '@types/node': '^22.10.2'
  '@noble/curves': '^1.8.1'
  '@noble/hashes': '^1.7.1'
  'blakejs': '^1.2.1'
  'base64url': '^3.0.1'
  '@radixdlt/babylon-core-api-sdk': '^1.2.3'
  '@radixdlt/babylon-gateway-api-sdk': '^1.6.1'
  '@radixdlt/radix-dapp-toolkit': '^2.0.3'
  '@radixdlt/radix-engine-toolkit': '^1.0.5'
  'neverthrow': '^8.0.0'
  'pino': '^9.4.0'
